# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true
  displayName: 'Instal Node 10.x'
- task: Npm@1
  inputs:
    command: 'install'
    verbose: true
  displayName: 'npm install and build'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test --- test/ --watchAll=false --reporters=default --reporters=jest-junit'
  displayName: 'run jest test'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'prune --production'
  displayName: 'npm prune left only production module'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Pipeline/$(Build.Repository.Name), ignore node_modules'
  inputs:
    TargetFolder: '$(build.artifactstagingdirectory)/Pipeline/$(Build.Repository.Name)'
    CleanTargetFolder: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish pipeline artifact'
  inputs:
    artifactName: 'refreshed-cache'
    targetPath: '$(Build.ArtifactStagingDirectory)'